version: '3.7'

services:
  bot:
    build:
      context: .
    command: python app.py
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - ".env.prod"

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ".env.prod"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: