version: '3.7'

services:
  bot:
    build:
      context: .
    command: python app.py
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - ".env.prod"

  postgres:
    image: postgres:latest
    restart: on-failure
    env_file:
      - ".env.prod"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}

volumes:
  postgres-data: